# @package _global_
# Tuned on mimic3_synthetic (2026-03-22)
dataset:
  max_number: 3000

model:
  encoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 64
    seq_hidden_units: 12
    br_size: 3
    fc_hidden_units: 3
    dropout_rate: 0.1
    num_layer: 1

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 64
    seq_hidden_units: 3
    br_size: 3
    fc_hidden_units: 3
    dropout_rate: 0.1
    num_layer: 1

exp:
  weights_ema: False
  balancing: grad_reverse
  max_epochs: 100
