"""
Pre-training dataset generation for DynamicCausalPFN.

After pre-training on these datasets, 
we will evaluate DynamicCausalPFN's performance on mimic test dataset - zeroshot, fewshot, fine-tuning

Therefore, a large-scale of pre-training dataset is generated
baesd on DAG structure following mimic data
3-dimensional vitals (Time-varying covariate),
1-dimensional static_feature (age),
1-dimensional treatment,
1-dimensional outcome.

sequence_length = 30
projection_horizon = 2 (tau = 2 + 1 = 3)

At each timestep,
1) treatment is generated by treatment network given current covariates (vitals + prev_outcome).
2) outcome is generated by outcome network given covariates (vitals + prev_outcome), treatment, static feature.

current outcome is then put into the next timestep's covariate.

And again generate treatment, outcome, .. and so on. 

Iterate this procedure to make timeseries of length = 30.

Given network parameters, noises, etc, a dataset is filled with M timeseries samples.

Do this for different parameters, and a large-scale dataset is generated. (N datasets).


We generate synthetic datasets (tasks) as follows. 
Each dataset is produced by:
- Sample ONE treatment network and ONE outcome network (fixed within the dataset).
- Generating M trajectories (samples), each of length T=seq_length.

DAG at each time step t:
	X_t -> A_t
	X_t -> Y_t
	A_t -> Y_t
	S    -> Y_t

Dynamics:
	vitals: 3-dimensional length=30 timeseries is sampled 
	initial outcome sampled from uniform distribution  
	X_0[0:3] <- vitals_0, X_0[3] <- initial outcome
	for t=0, ...T-2:
		A_t ~ Bernoulli( sigmoid ( f_A(X_t) ) )
		Y_t(a) = f_Y([X_t, a, S]) for a in {0, 1}
		Y_t = Y_t(A_t)
		X_{t+1}[3] <- Y_t
		X_{t+1}[0:3] <- vitals_{t+1}
	
Outputs are aligned with mimic_iii.semi_synthetic_dataset.py keys
	outcomes, static_features, vitals, treatments, sequence_lengths
	"""

from typing import Callable, Dict, Optional, Tuple

import numpy as np
import pandas as pd

import functools
from typing import Optional

import numpy as np
from joblib import Parallel, delayed
from sklearn.gaussian_process.kernels import (
    RBF,
    ConstantKernel,
    DotProduct,
    ExpSineSquared,
    Kernel,
    RationalQuadratic,
    WhiteKernel,
)
from tqdm.auto import tqdm


def _sample_initial_outcomes(num_patients: int) -> np.ndarray:
	"""
	Sample initial outcomes 
	"""
	x0 = np.random.lognormal(mean=0.0, sigma=1.0, size=num_patients)
	x0 = np.clip(x0, 1e-3, None)
	
	return x0 


def _sigmoid(x: np.ndarray) -> np.ndarray:
	return 1.0 / (1.0 + np.exp(-np.clip(x, -50, 50)))


# --------------------------------------------------------------------------------------
# Stochastic MLP primitives 
# --------------------------------------------------------------------------------------

class TreatmentAssigner:
	"""
	Stochastic propensity network:
		logit = f_A(X) with additive noise per layer,
		A ~ Bernoulli(sigmoid(logit))
	The sampled network parameters are FIXED for the whole dataset (task),
	but exogenous noise is sampled per call (per sample/time).
	"""

	def __init__(
			self, 
			prior_layers: Callable[[], int] = lambda: np.random.randint(2, 4), # (3, 5)
			prior_hidden_size: Callable[[], int] = lambda: np.random.randint(8, 30), # (8, 20)
			weight_std:float=1.0, # 0.8
			activation: Callable[[np.ndarray], np.ndarray] = np.tanh,
	):
		self.prior_layers=prior_layers
		self.prior_hidden_size=prior_hidden_size
		self.weight_std=weight_std
		self.activation=activation

		self.layer_weights: list[np.ndarray] = []
		self.layer_biases: list[np.ndarray] = []
		self.noise_samplers: list[Callable[[Tuple[int, int]], np.ndarray]] = []

		self.initialized: bool=False
		self.propensity_scores: Optional[np.ndarray] = None 
	
	def _sample_noise_distribution(self) -> Callable[[Tuple[int, int]], np.ndarray]:
		dist_type = np.random.choice(["normal", "uniform", "laplace", "logistic"])
		if dist_type == "normal":
			scale = np.random.uniform(0.05, 0.5) # (0.1, 1.0)
			return lambda shape: np.random.normal(0.0, scale, size=shape)
		if dist_type == "uniform":
			scale = np.random.uniform(0.05, 0.5) # (0.1, 1.0)
			return lambda shape: np.random.uniform(-scale, scale, size=shape)
		if dist_type == "laplace":
			scale = np.random.uniform(0.05, 0.3) # (0.1, 0.5)
			return lambda shape: np.random.laplace(0.0, scale, size=shape)
		# logistic
		scale = np.random.uniform(0.05, 0.3) # (0.1, 0.5)
		return lambda shape: np.random.logistic(0.0, scale, size=shape)
	
	def sample_new_mechanism(self, input_dim:int) -> None:
		depth = int(np.clip(self.prior_layers(), 2, 3)) # 3, 5
		hidden = int(self.prior_hidden_size())

		dims = [input_dim] + ([hidden] * (depth - 2)) + [1]

		self.layer_weights = []
		self.layer_biases = []
		self.noise_samplers = []

		for din, dout in zip(dims[:-1], dims[1:]):
			W = np.random.normal(0.0, self.weight_std / np.sqrt(max(din, 1)), size=(din, dout)) # normal(0.0, self.weight_std)
			b = np.random.normal(0.0, self.weight_std, size=(dout,))
			self.layer_weights.append(W)
			self.layer_biases.append(b)
			self.noise_samplers.append(self._sample_noise_distribution())
		
		self.initialized = True
	
	def _forward_logits(self, X: np.ndarray) -> np.ndarray:
		n = X.shape[0]
		h = X 
		for li, (W, b, noise_sampler) in enumerate(zip(self.layer_weights, self.layer_biases, self.noise_samplers)):
			eps = noise_sampler((n, W.shape[1]))
			h = h @ W + b + eps
			if li < len(self.layer_weights) - 1:
				h = self.activation(h)
		return h.reshape(-1)
	
	def generate_treatments(self, X: np.ndarray, resample: bool=False) -> np.ndarray:
		if (not self.initialized) or resample:
			self.sample_new_mechanism(input_dim=X.shape[1])
		
		logits = self._forward_logits(X)
		p = _sigmoid(logits)
		self.propensity_scores = p
		A = np.random.binomial(1, p)
		return A 
	

class OutcomeGenerator:
	"""
	Stochastic outcome network with edge-drop on hidden weights:
		Y(a) = f_Y([X, a, S]) with additive noise per layer
	Potential outcomes Y(0), Y(1) share the SAME sampled exogenous noise per call
	(per sample/time).
	"""
	def __init__(
			self, 
			prior_layers: Callable[[], int] = lambda: np.random.randint(2, 4), # (3, 6)
			prior_hidden_size: Callable[[], int] = lambda: np.random.randint(8, 30), # (10, 25)
			weight_std: float=1.0,
			edge_drop_prob: float=0.3,
			activation: Callable[[np.ndarray], np.ndarray] = np.tanh,
	):
		self.prior_layers=prior_layers
		self.prior_hidden_size=prior_hidden_size
		self.weight_std=weight_std
		self.edge_drop_prob=edge_drop_prob
		self.activation=activation


		self.layer_weights: list[np.ndarray] = []
		self.layer_biases: list[np.ndarray] = []
		self.noise_samplers: list[Callable[[Tuple[int, int]], np.ndarray]] = []

		self.initialized: bool=False

	
	def _sample_noise_distribution(self) -> Callable[[Tuple[int, int]], np.ndarray]:
		dist_type = np.random.choice(["normal", "uniform", "laplace", "logistic"])
		if dist_type == "normal":
			scale = np.random.uniform(0.05, 0.5) # (0.1, 1.0)
			return lambda shape: np.random.normal(0.0, scale, size=shape)
		if dist_type == "uniform":
			scale = np.random.uniform(0.05, 0.5) # (0.1, 1.0)
			return lambda shape: np.random.uniform(-scale, scale, size=shape)
		if dist_type == "laplace":
			scale = np.random.uniform(0.05, 0.3) # (0.1, 0.5)
			return lambda shape: np.random.laplace(0.0, scale, size=shape)
		scale = np.random.uniform(0.05, 0.3) # (0.1, 0.5)
		return lambda shape: np.random.logistic(0.0, scale, size=shape)
	
	def sample_new_mechanism(self, input_dim:int) -> None:
		depth = int(np.clip(self.prior_layers(), 2, 3)) # 3, 6
		hidden = int(self.prior_hidden_size())

		dims = [input_dim] + ([hidden] * (depth - 2)) + [1]

		self.layer_weights = []
		self.layer_biases = []
		self.noise_samplers = []

		for li, (din, dout) in enumerate(zip(dims[:-1], dims[1:])):
			W = np.random.normal(0.0, self.weight_std / np.sqrt(max(din, 1)), size=(din, dout)) # normal(0.0, self.weight_std)

			# Drop edges for hidden layers only (not output layer)
			if self.edge_drop_prob > 0.0 and li < len(dims) - 2:
				mask = (np.random.rand(*W.shape) > self.edge_drop_prob).astype(W.dtype)
				W = W * mask 
			
			b = np.random.normal(0.0, self.weight_std, size=(dout,))
			self.layer_weights.append(W)
			self.layer_biases.append(b)
			self.noise_samplers.append(self._sample_noise_distribution())
		
		self.initialized = True
	
	def _forward_raw(self, Z: np.ndarray, noise_list: Optional[list[np.ndarray]] = None) -> Tuple[np.ndarray, list[np.ndarray]]:
		n = Z.shape[0]
		h = Z
		used_noise: list[np.ndarray] = []

		for li, (W, b, noise_sampler) in enumerate(zip(self.layer_weights, self.layer_biases, self.noise_samplers)):
			eps = noise_sampler((n, W.shape[1])) if noise_list is None else noise_list[li]
			used_noise.append(eps)

			h = h @ W + b + eps
			if li < len(self.layer_weights) - 1:
				h = self.activation(h)
		
		return h.reshape(-1), used_noise
	
	def generate_outcomes(
			self, 
			X: np.ndarray,
			A: np.ndarray,
			S: np.ndarray,
			resample: bool = False,
	) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
		"""
		Args:
			X: (n, dx) - Note that, in the covariates dimension dx, [0:dx-1] is vitals and [dx-1] is prev_outcome  
			A: (n,) int {0, 1}
			S: (n, ds)
		Returns:
			Y: (n,) factual
			Y0: (n,) potential under 0
			Y1: (n,) potential under 1
		"""
		if (not self.initialized) or resample:
			input_dim = X.shape[1] + 1 + S.shape[1]
			self.sample_new_mechanism(input_dim=input_dim)
		
		n = X.shape[0]
		a0 = np.zeros((n, 1), dtype=X.dtype)
		a1 = np.ones((n, 1), dtype=X.dtype)

		z0 = np.concatenate([X, a0, S], axis=1)
		z1 = np.concatenate([X, a1, S], axis=1)

		# Shared exogenous noise between Y(0) and Y(1) per sample/time
		_, noise = self._forward_raw(z0, noise_list=None)
		y0, _ = self._forward_raw(z0, noise_list=noise)
		y1, _ = self._forward_raw(z1, noise_list=noise)

		y = np.where(A.astype(bool), y1, y0)

		return y, y0, y1 


class VitalGenerator:
	"""
	synthetic multivariate time-series 
	using the Linear Coregionalization Model introduced by the authors of TimePFN
	which is built upon the kernel-synth method introduced by the authors of Chronos.

	Here, we use this method to generate num_patients number of 
	3-dimensional vitals with seq_length=30.
	"""
	def __init__(
			self, 
			num_patients:int=100,
			max_kernels:int=5,
			num_channels:int=3,
			seq_length:int=30,
			dirichlet_min:float=0.1,
			dirichlet_max:float=0.9,
			weibull_shape:float=2,
			weibull_scale:float=3
	):
		self.num_patients=num_patients
		self.num_channels=num_channels
		self.max_kernels=max_kernels
		self.dirichlet_min = dirichlet_min
		self.dirichlet_max=dirichlet_max
		self.weibull_shape=weibull_shape
		self.weibull_scale=weibull_scale

		self.LENGTH = seq_length

		self.KERNEL_BANK = [
			ExpSineSquared(periodicity=24 / self.LENGTH),  # H
			ExpSineSquared(periodicity=48 / self.LENGTH),  # 0.5H
			ExpSineSquared(periodicity=96 / self.LENGTH),  # 0.25H
			ExpSineSquared(periodicity=24 * 7 / self.LENGTH),  # H
			ExpSineSquared(periodicity=48 * 7 / self.LENGTH),  # 0.5H
			ExpSineSquared(periodicity=96 * 7 / self.LENGTH),  # 0.25H
			ExpSineSquared(periodicity=7 / self.LENGTH),  # D
			ExpSineSquared(periodicity=14 / self.LENGTH),  # 0.5D
			ExpSineSquared(periodicity=30 / self.LENGTH),  # D
			ExpSineSquared(periodicity=60 / self.LENGTH),  # 0.5D
			ExpSineSquared(periodicity=365 / self.LENGTH),  # D
			ExpSineSquared(periodicity=365 * 2 / self.LENGTH),  # 0.5D
			ExpSineSquared(periodicity=4 / self.LENGTH),  # W
			ExpSineSquared(periodicity=26 / self.LENGTH),  # W
			ExpSineSquared(periodicity=52 / self.LENGTH),  # W
			ExpSineSquared(periodicity=4 / self.LENGTH),  # M
			ExpSineSquared(periodicity=6 / self.LENGTH),  # M
			ExpSineSquared(periodicity=12 / self.LENGTH),  # M
			ExpSineSquared(periodicity=4 / self.LENGTH),  # Q
			ExpSineSquared(periodicity=4 * 10 / self.LENGTH),  # Q
			ExpSineSquared(periodicity=10 / self.LENGTH),  # Y
			DotProduct(sigma_0=0.0),
			DotProduct(sigma_0=1.0),
			DotProduct(sigma_0=10.0),
			RBF(length_scale=0.1),
			RBF(length_scale=1.0),
			RBF(length_scale=10.0),
			RationalQuadratic(alpha=0.1),
			RationalQuadratic(alpha=1.0),
			RationalQuadratic(alpha=10.0),
			WhiteKernel(noise_level=0.1),
			WhiteKernel(noise_level=1.0),
			ConstantKernel(),
		]
		
	def random_binary_map(self, a: Kernel, b: Kernel):
		"""
		Applies a random binary operator (+ or *) with equal probability
		on kernels ``a`` and ``b``.

		Parameters
		---------
		a
			A GP kernel.
		b
			A GP kernel.
		
		Returns
		------
			The compositte kernel `a + b` or `a * b`.
		"""
		binary_maps = [lambda x, y: x + y, lambda x, y: x * y]
		return np.random.choice(binary_maps)(a, b)
	
	
	def sample_from_gp_prior_efficient(self, kernel: Kernel, X: np.ndarray, random_seed: Optional[int] = None,
									method: str='eigh',):
		"""
		Draw a sample from a GP prior. An efficient version that allows specification
		of the sampling method. The default sampling method used in GaussianProcessRegressor
		is based on SVD which is significantly slower than alternatives such as `eigh` and `cholesky`.
		
		Parameters
		---------
		kernel
			The GP covariance kernel.
		X
			The input "time" points.
		random_seed, optional
			The random seed for sampling, by default None.
		method, optional
			The sampling method form multivariate_normal, by default `eigh`.
			
		Returns
		------
			A time series sampled from the GP prior.
		"""
		if X.ndim == 1:
			X = X[:, None]
		
		assert X.ndim == 2

		cov = kernel(X)
		ts = np.random.default_rng(seed=random_seed).multivariate_normal(
			mean=np.zeros(X.shape[0]), cov=cov, method=method
		)
		return ts
	
	def generate_time_series(self, dirichlet_min, dirichlet_max, weibull_shape, weibull_scale, 
						  max_kernels, num_channels, seq_length):
		"""Generate a synthetic time series from LMC_Synth."""
		while True:
			X = np.linspace(0, 1, seq_length)

			# sample number of latent functions from weibull distribution
			latent_num = np.rint(np.random.weibull(weibull_shape, 1)*weibull_scale + 1)
			latent_num = np.clip(latent_num, 2, num_channels)
			latent_num = int(latent_num[0])

			# now we will have latent num of latent functions. 
			# Each latent function will have a random number of kernels
			kernel_numbers = np.random.randint(1, max_kernels + 1, size=latent_num)
			# now that we have the number of kernels for each latent function
			# we will sample the kernels for each latent function
			latent_kernels = [functools.reduce(self.random_binary_map, 
									  np.random.choice(self.KERNEL_BANK, num_kernels, replace=True))
									  for num_kernels in kernel_numbers]
			
			try:
				# now we have the kernels for each latent function
				# we will now sample the latent functions
				latent_functions = np.array([self.sample_from_gp_prior_efficient(
					kernel=kernel, X=X) for kernel in latent_kernels])
				# sample dirichlet parameter between dirichlet_min and dirichlet_max uniformly
				dirichlet = np.random.uniform(dirichlet_min, dirichlet_max)
				# now sample the weights for each latent function
				weights = np.random.dirichlet(dirichlet*np.ones(latent_num), size=num_channels)
				# now we will combine the latent functions with the weights
				ts = np.dot(weights, latent_functions)
			except np.linalg.LinAlgError as err:
				print("Error caught:", err)
				continue 

			return ts 
	
	def generate_many_vitals(self):
		many_vitals = Parallel(n_jobs=-1)(
			delayed(self.generate_time_series)(max_kernels=self.max_kernels,
									  num_channels=self.num_channels,
									  dirichlet_min=self.dirichlet_min,
									  dirichlet_max=self.dirichlet_max,
									  weibull_shape=self.weibull_shape,
									  weibull_scale=self.weibull_scale,
									  seq_length=self.LENGTH)
									  for _ in tqdm(range(self.num_patients))
		)
		return many_vitals # list of num_patients time-series, each has [num_channels, seq_length]
	""""""


# --------------------------------------------------------------------------------------
# Main generator (aligned with mimic outputs)
# --------------------------------------------------------------------------------------

def generate_pretraining_dataset(
		num_samples: int,
		seq_length: int,
		*,
		seed: Optional[int] = None,
		treatment_assigner: Optional[TreatmentAssigner] = None,
		outcome_generator: Optional[OutcomeGenerator] = None,
		vital_generator: Optional[VitalGenerator] = None,
		initial_outcome_sampler: Optional[Callable[[int], np.ndarray]] = None,
		static_feature_sampler: Optional[Callable[[int], np.ndarray]] = None,
) -> Dict[str, np.ndarray]:
	"""
	Generate ONE synthetic dataset (one task) with num_samples trajectories.
	
	- A single treatment network and outcome network is sampled once and reused.
	- num_samples of len=seq_length timeseries (vitals) is sampled.
		Each patient trajectory gets it own sampled vital time series.
	- At each t:
		Covariate X_t is composed with vitals_t and previous outcome Y_{t-1}
		A_t sampled from treatment net given current covariate X_t 
		Y_t sampled from outcome net given X_t, A_t, S
	
	Returns dict compatible with MIMIC semi-synthetic interface:
		outcomes, static_features, vitals, treatments, sequence_lengths.
	"""

	if seed is not None:
		np.random.seed(seed)
	
	# Sample patient-level static features and initial outcomes
	if initial_outcome_sampler is None:
		initial_outcomes = _sample_initial_outcomes(num_samples)
	else:
		initial_outcomes = initial_outcome_sampler(num_samples)
	
	if static_feature_sampler is None:
		static_features = np.random.choice(np.arange(10, 90), size=num_samples)
	else:
		static_features = static_feature_sampler(num_samples)
	
	# Static feature tensor S (N, 1).
	S = static_features.reshape(-1, 1)

	# Create / sample mechanisms (fixed within this dataset)
	if treatment_assigner is None:
		treatment_assigner = TreatmentAssigner()
	if outcome_generator is None:
		outcome_generator = OutcomeGenerator()
	
	# Create num_patients vitals with length=seq_length.
	# Each vitals is used for each patient trajectory.
	if vital_generator is None:
		vital_generator = VitalGenerator(num_patients=num_samples, seq_length=seq_length)
	
	# vitals: [N, T, 3]
	vitals = np.asarray(vital_generator.generate_many_vitals()) #[num_samples, vital_dim, seq_length]
	vitals = np.transpose(vitals, (0, 2, 1)) # [num_samples, seq_length, vital_dim(3)]

	# Raw outcome trajectory: [N, T]
	outcomes = np.zeros((num_samples, seq_length))

	# Raw treatment trajectory: [N, T, 1]
	# treatments[:, 0] stays zero, because row 0 has no previous treatment
	treatments = np.zeros((num_samples, seq_length, 1))

	# Number of valid one-step transitions
	sequence_lengths = np.full((num_samples, ), seq_length - 1)

	# Initial outcome at time 0
	outcomes[:, 0] = initial_outcomes

	# X_t = [vitals_t(3), previous_outcome(1)] => dim 4
	treatment_assigner.sample_new_mechanism(input_dim=4)
	outcome_generator.sample_new_mechanism(input_dim=4 + 1 + S.shape[1])
	
	# vetorized over patients
	for t in range(seq_length - 1):
		x_t = np.concatenate([vitals[:, t, :], outcomes[:, t][:, None]], axis=1) # (N, 4)

		a_t = treatment_assigner.generate_treatments(x_t, resample=False) # (N,)
		treatments[:, t+1, 0] = a_t 

		y_next, _, _ = outcome_generator.generate_outcomes(x_t, a_t, S, resample=False)
		outcomes[:, t+1] = y_next 

	outputs = {
		"outcomes": outcomes, # (N, T)
		"treatments": treatments, # (N, T, 1)
		"vitals":vitals, # (N, T, 3)
		"sequence_lengths": sequence_lengths, # (N,)
		"static_features": static_features, # (N, ) or (N, 1) 
	}

	return outputs


def get_pretrain_scaling_params(sim: Dict[str, np.ndarray]):
	"""
	Compute per-feature normalisation statistics for:
		- outcomes
		- vitals
		- static_features
	
	Uses only active transition steps for outcomes and vitals.
	"""

	outcomes = np.asarray(sim['outcomes'])
	vitals = np.asarray(sim['vitals'])
	static_features = np.asarray(sim['static_features'])
	sequence_lengths = np.asarray(sim['sequence_lengths']).astype(int)

	if outcomes.ndim == 2:
		outcomes = outcomes[:, :, None]
	
	if vitals.ndim == 2:
		vitals = vitals[:, :, None]
	
	if static_features.ndim == 1:
		static_features = static_features[:, None]
	
	n, t_out, d_out = outcomes.shape
	_, t_vit, d_vit = vitals.shape

	active_mask = np.zeros((n, t_out - 1), dtype=bool)
	for i in range(n):
		active_len = min(int(sequence_lengths[i]), t_out - 1)
		active_mask[i, :active_len] = True
	
	active_outputs = outcomes[:, 1:, :][active_mask]
	active_vitals = vitals[:, 1:, :][active_mask]

	if active_outputs.ndim == 1:
		active_outputs = active_outputs[:, None]
	
	if active_vitals.ndim == 1:
		active_vitals = active_vitals[:, None]
	
	output_means = active_outputs.mean(axis=0)
	output_stds = active_outputs.std(axis=0)
	output_stds = np.where(output_stds ==0, 1.0, output_stds)

	vitals_means = active_vitals.mean(axis=0)
	vitals_stds = active_vitals.std(axis=0)
	vitals_stds = np.where(vitals_stds==0, 1.0, vitals_stds)

	static_features_means = static_features.mean(axis=0)
	static_features_stds = static_features.std(axis=0)
	static_features_stds = np.where(static_features_stds==0, 1.0, static_features_stds)

	return {
		'output_means':output_means,
		'output_stds':output_stds,
		'vitals_means':vitals_means,
		'vitals_stds':vitals_stds,
		'static_features_means':static_features_means,
		'static_features_stds':static_features_stds,
	}
	

# Generate N datasets (tasks)
def generate_many_pretraining_datasets(
		num_datasets: int,
		samples_per_dataset: int,
		seq_length: int,
		*, 
		base_seed: Optional[int] = None,
		**kwargs,
) -> list[Dict[str, np.ndarray]]:
	"""
	Returns a list of datasets [D_0, ..., D_{N-1}], each generated with a different mechanism.
	Useful if PFN training samples "a dataset/task" per batch element.
	"""
	out = []
	for i in range(num_datasets):
		seed_i = None if base_seed is None else base_seed + i
		ds = generate_pretraining_dataset(
			samples_per_dataset, 
			seq_length, 
			seed=seed_i, 
			**kwargs,
		)
		out.append(ds)
	return out 



# Main execution
if __name__ == "__main__":
    # Generate 10k datasets with 1024 samples each
    datasets = generate_many_pretraining_datasets(
        # num_datasets=10000,
		num_datasets=10,
        samples_per_dataset=100,
        seq_length=30,
        base_seed=42
    )
    print(datasets[0].keys())
    print(len(datasets))
    print(datasets[0]['outcomes'].shape)
    print(datasets[0]['treatments'].shape)
    print(datasets[0]['vitals'].shape)
    print(datasets[0]['static_features'].shape)	
    print(datasets[0]['treatments'])
