# @package _global_
# Tuned on mimic3_synthetic (2026-03-22)
dataset:
  max_number: 3000

model:
  g_net:
    optimizer:
      learning_rate: 0.01
    num_layer: 1
    batch_size: 64
    seq_hidden_units: 12
    fc_hidden_units: 12
    dropout_rate: 0.2
    r_size: 6

exp:
  max_epochs: 100
