# @package _global_
# Tuned on mimic3_synthetic (2026-03-22)
dataset:
  max_number: 3000

model:
  gt:
    optimizer:
      learning_rate: 0.001
    batch_size: 32
    seq_hidden_units: 6
    hr_size: 3
    fc_hidden_units: 6
    dropout_rate: 0.1
    num_layer: 1
    num_heads: 3

    self_positional_encoding:
      max_relative_position: 15

exp:
  max_epochs: 100
